# Generated by Django 5.2.7 on 2025-12-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Log",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("msg", models.CharField(max_length=100)),
                ("filename", models.CharField(max_length=100)),
                ("levelname", models.CharField(max_length=100)),
                ("asctime", models.DateTimeField()),
            ],
            options={
                "verbose_name": "log",
                "verbose_name_plural": "logs",
            },
        ),
    ]
