# Generated by Django 5.2.7 on 2026-01-21 19:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("subscription", models.JSONField(verbose_name="Push subscription data")),
                (
                    "browser",
                    models.CharField(
                        choices=[
                            ("chrome", "Chrome"),
                            ("firefox", "Firefox"),
                            ("safari", "Safari"),
                            ("edge", "Edge"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="Browser",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Is active")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
            ],
            options={
                "verbose_name": "device",
                "verbose_name_plural": "devices",
            },
        ),
    ]
