# Generated by Django 5.2.7 on 2026-01-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_device"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="is_admin",
            field=models.BooleanField(default=False, verbose_name="Is admin"),
        ),
    ]
