# Generated by Django 5.2.7 on 2026-02-14 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_device_is_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="log",
            name="stacktrace",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="log",
            name="variables",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
