# Generated by Django 5.2.7 on 2026-03-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_add_stacktrace_and_variables_to_log"),
    ]

    operations = [
        migrations.CreateModel(
            name="Auth",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("token", models.CharField(max_length=64, unique=True, verbose_name="Token")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
            ],
            options={
                "verbose_name": "auth",
                "verbose_name_plural": "auth",
            },
        ),
    ]
