# Generated by Django 5.2.7 on 2025-12-29 21:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VoltageLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("voltage", models.DecimalField(decimal_places=2, max_digits=7, verbose_name="Voltage")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
            ],
            options={
                "verbose_name": "voltage log",
                "verbose_name_plural": "voltage logs",
                "ordering": ("-created_at",),
            },
        ),
    ]
