# Generated by Django 5.2.7 on 2026-01-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "currency",
                    models.CharField(
                        choices=[("USD", "US Dollar"), ("EUR", "Euro"), ("RUB", "Russian Ruble")],
                        db_index=True,
                        max_length=3,
                    ),
                ),
                ("rate", models.DecimalField(decimal_places=4, max_digits=10)),
                ("scale", models.PositiveIntegerField(default=1)),
                ("date", models.DateField(db_index=True)),
                ("data", models.JSONField(default=dict)),
                ("synced_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "exchange rate",
                "verbose_name_plural": "exchange rates",
                "ordering": ["-date"],
                "unique_together": {("currency", "date")},
            },
        ),
    ]
