# Generated by Django 5.0.3 on 2024-03-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sensors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensor",
            name="synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
