# Generated by Django 5.0.3 on 2024-03-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensors", "0002_sensor_synced_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("type", models.CharField(choices=[("IN", "Incoming"), ("OUT", "Outgoing")], max_length=32)),
                ("synced_at", models.DateTimeField(auto_now_add=True)),
                ("synced_count", models.IntegerField()),
            ],
            options={
                "verbose_name": "sync log",
                "verbose_name_plural": "sync logs",
            },
        ),
    ]
