# Generated by Django 5.2.4 on 2025-07-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sensors", "0003_synclog"),
    ]

    operations = [
        migrations.CreateModel(
            name="RawSensor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("address", models.CharField(max_length=32)),
                ("temp", models.DecimalField(decimal_places=2, max_digits=7)),
                ("is_synced", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "raw sensor",
                "verbose_name_plural": "raw sensors",
                "db_table": "sensors_raw_data",
                "managed": False,
            },
        ),
        migrations.RemoveField(
            model_name="sensor",
            name="external_id",
        ),
        migrations.RemoveField(
            model_name="sensor",
            name="synced_at",
        ),
        migrations.AddField(
            model_name="sensor",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="sensor",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="sensor",
            name="humidity",
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
