# Generated by Django 5.2.7 on 2025-12-08 07:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sensors", "0004_rawsensor_remove_sensor_external_id_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Sensor",
            new_name="SensorLog",
        ),
        migrations.DeleteModel(
            name="SyncLog",
        ),
        migrations.DeleteModel(
            name="RawSensor",
        ),
    ]
