# Generated by Django 5.2.7 on 2025-12-08 08:57

from django.db import migrations, models

from odin.apps.sensors.models import SensorType


class Migration(migrations.Migration):
    dependencies = [
        ("sensors", "0005_rename_sensor_sensorlog_delete_synclog_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sensor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sensor_id", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=32)),
                ("type", models.CharField(choices=SensorType.choices, max_length=32)),
                ("context", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "sensor",
                "verbose_name_plural": "sensors",
            },
        ),
    ]
