# Generated by Django 5.2.7 on 2025-12-08 09:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sensors", "0006_sensor"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensor",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
