# Generated by Django 5.2.7 on 2025-12-08 09:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sensors", "0007_sensor_is_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sensorlog",
            options={"verbose_name": "sensor log", "verbose_name_plural": "sensor logs"},
        ),
    ]
