# Generated by Django 5.2.7 on 2025-12-08 15:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sensors", "0008_alter_sensorlog_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sensorlog",
            old_name="created_at",
            new_name="synced_at",
        ),
    ]
