# Generated by Django 5.2.7 on 2025-12-08 15:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sensors", "0009_rename_created_at_sensorlog_synced_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sensorlog",
            old_name="updated_at",
            new_name="created_at",
        ),
    ]
