# Generated by Django 5.2.7 on 2025-12-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sensors", "0010_rename_updated_at_sensorlog_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sensorlog",
            name="created_at",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
