# Generated by Django 5.2.7 on 2025-12-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sensors", "0011_alter_sensorlog_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sensor",
            name="context",
            field=models.JSONField(default=dict, verbose_name="Context"),
        ),
        migrations.AlterField(
            model_name="sensor",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="sensor",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is active"),
        ),
        migrations.AlterField(
            model_name="sensor",
            name="name",
            field=models.CharField(max_length=32, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="sensor",
            name="sensor_id",
            field=models.CharField(max_length=32, verbose_name="Sensor ID"),
        ),
        migrations.AlterField(
            model_name="sensor",
            name="type",
            field=models.CharField(
                choices=[("DS18B20", "DS18B20"), ("ESP8266", "ESP8266")], max_length=32, verbose_name="Type"
            ),
        ),
        migrations.AlterField(
            model_name="sensor",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
    ]
