# Generated by Django 5.2.7 on 2026-01-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sensors", "0012_alter_sensor_context_alter_sensor_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensor",
            name="linked_sensor_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=32, null=True, verbose_name="Linked sensor ID"
            ),
        ),
        migrations.AddField(
            model_name="sensor",
            name="relay_id",
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, verbose_name="Relay ID"),
        ),
        migrations.AddField(
            model_name="sensor",
            name="is_visible",
            field=models.BooleanField(default=True, verbose_name="Is visible"),
        ),
        migrations.AlterField(
            model_name="sensor",
            name="sensor_id",
            field=models.CharField(db_index=True, max_length=32, verbose_name="Sensor ID"),
        ),
    ]
