# Generated by Django 5.2.7 on 2026-01-14 07:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sensors", "0013_sensor_relay_id_alter_sensor_sensor_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensor",
            name="humidity_offset",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.0"), max_digits=7, verbose_name="Humidity offset"
            ),
        ),
        migrations.AddField(
            model_name="sensor",
            name="temp_offset",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.0"), max_digits=7, verbose_name="Temp offset"
            ),
        ),
    ]
