# Generated by Django 5.2.7 on 2026-01-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sensors", "0014_sensor_humidity_offset_sensor_temp_offset"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensor",
            name="order",
            field=models.IntegerField(default=0, verbose_name="Order"),
        ),
    ]
