# Generated by Django 6.0.8 on 2026-09-24 21:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sensors", "0017_sensor_relay_fk"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sensor",
            name="relay_id_old",
        ),
        migrations.RemoveField(
            model_name="sensorlog",
            name="sensor_id_old",
        ),
    ]
