# Generated by Django 6.0.8 on 2026-09-24 21:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sensors", "0018_remove_sensor_relay_id_old_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensor",
            name="humidity",
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name="sensor",
            name="temp",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.0"), max_digits=7),
        ),
    ]
