# Generated by Django 6.0.8 on 2026-09-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sensors", "0021_remove_sensor_linked_sensor_id_old"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sensor",
            name="temp",
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
