# Generated by Django 5.2.7 on 2025-12-17 08:56

from django.db import migrations, models

from odin.apps.relays.models import RelayType


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Relay",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("relay_id", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=32)),
                (
                    "type",
                    models.CharField(choices=RelayType.choices, max_length=32),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("context", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "relay",
                "verbose_name_plural": "relays",
            },
        ),
    ]
