# Generated by Django 5.2.7 on 2025-12-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("relays", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relay",
            name="context",
            field=models.JSONField(default=dict, verbose_name="Context"),
        ),
        migrations.AlterField(
            model_name="relay",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="relay",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is active"),
        ),
        migrations.AlterField(
            model_name="relay",
            name="name",
            field=models.CharField(max_length=32, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="relay",
            name="relay_id",
            field=models.CharField(max_length=32, verbose_name="Relay ID"),
        ),
        migrations.AlterField(
            model_name="relay",
            name="type",
            field=models.CharField(
                choices=[("PUMP", "Pump"), ("SERVO", "Servo"), ("VALVE", "Valve")], max_length=32, verbose_name="Type"
            ),
        ),
        migrations.AlterField(
            model_name="relay",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
    ]
