# Generated by Django 5.2.7 on 2026-01-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("relays", "0002_alter_relay_context_alter_relay_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relay",
            name="relay_id",
            field=models.CharField(db_index=True, max_length=32, verbose_name="Relay ID"),
        ),
    ]
