# Generated by Django 5.2.7 on 2026-01-09 08:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("relays", "0003_alter_relay_relay_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="relay",
            name="force_state",
            field=models.CharField(
                blank=True,
                choices=[("ON", "ON"), ("OFF", "OFF")],
                max_length=32,
                null=True,
                verbose_name="Force relay state",
            ),
        ),
    ]
