# Generated by Django 5.2.7 on 2026-01-23 08:34

from django.db import migrations


def convert_legacy_schedule_to_periodic(apps, schema_editor):
    """Convert old {day: {hour: boolean}} schedule format to new periodic format."""
    Relay = apps.get_model("relays", "Relay")

    for relay in Relay.objects.all():
        if not relay.context or "schedule" not in relay.context:
            continue

        schedule = relay.context["schedule"]
        if "periods" in schedule:
            continue

        # Convert legacy format to periodic format
        # Since periods now apply to all days, merge all day schedules
        all_active_hours = set()
        for _, hours in schedule.items():
            for hour_str, is_active in hours.items():
                if is_active:
                    all_active_hours.add(int(hour_str))
        if not all_active_hours:
            continue

        periods = []
        current_period = None
        active_hours = sorted(list(all_active_hours))
        for hour in active_hours:
            if current_period is None:
                current_period = {"start": hour, "end": hour}
            elif hour == current_period["end"] + 1:
                current_period["end"] = hour
            else:
                period = {
                    "start_time": f"{current_period['start']:02d}:00",
                    "end_time": f"{(current_period['end'] + 1) % 24:02d}:00",
                }
                if relay.type == "PUMP":
                    period["target_state"] = "ON"
                if relay.type == "SERVO":
                    period["target_temp"] = 25.0
                periods.append(period)

                current_period = {"start": hour, "end": hour}

        if current_period:
            period = {
                "start_time": f"{current_period['start']:02d}:00",
                "end_time": f"{(current_period['end'] + 1) % 24:02d}:00",
            }
            if relay.type == "PUMP":
                period["target_state"] = "ON"
            if relay.type == "SERVO":
                period["target_temp"] = 25.0
            periods.append(period)

        if periods:
            relay.context["schedule"] = {"periods": periods}
            relay.save(update_fields=["context"])


def reverse_convert_periodic_to_legacy(apps, schema_editor):
    """Reverse migration: convert periodic format back to legacy format."""
    Relay = apps.get_model("relays", "Relay")

    for relay in Relay.objects.all():
        if not relay.context or "schedule" not in relay.context:
            continue

        schedule = relay.context["schedule"]

        # Skip if already in legacy format
        if "periods" not in schedule:
            continue

        # Convert periodic format back to legacy format
        legacy_schedule = {str(d): {f"{h:02d}": False for h in range(24)} for d in range(7)}

        for period in schedule["periods"]:
            start_hour = int(period["start_time"].split(":")[0])
            end_hour = int(period["end_time"].split(":")[0])

            # Apply to all days since periods no longer have day filtering
            for day in range(7):
                day_str = str(day)
                if end_hour > start_hour:
                    # Same day period
                    for hour in range(start_hour, end_hour):
                        legacy_schedule[day_str][f"{hour:02d}"] = True
                else:
                    # Overnight period
                    for hour in range(start_hour, 24):
                        legacy_schedule[day_str][f"{hour:02d}"] = True
                    for hour in range(0, end_hour):
                        legacy_schedule[day_str][f"{hour:02d}"] = True

        # Update context with legacy format
        relay.context["schedule"] = legacy_schedule
        relay.save(update_fields=["context"])


class Migration(migrations.Migration):
    dependencies = [
        ("relays", "0004_relay_force_state"),
    ]

    operations = [
        migrations.RunPython(convert_legacy_schedule_to_periodic, reverse_code=reverse_convert_periodic_to_legacy),
    ]
