# Generated by Django 6.0.8 on 2026-09-11 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("relays", "0005_convert_schedule_to_periodic"),
    ]

    operations = [
        migrations.AddField(
            model_name="relay",
            name="related_relay",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="related_relays",
                to="relays.relay",
                verbose_name="Related relay",
            ),
        ),
    ]
