# Generated by Django 6.0.8 on 2026-09-17 21:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("relays", "0006_relay_related_relay"),
    ]

    operations = [
        migrations.AddField(
            model_name="relay",
            name="mode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("UNKNOWN", "Unknown"),
                    ("FALLBACK", "Fallback"),
                    ("FORCED", "Forced"),
                    ("IGNORED", "Ignored"),
                    ("SUMMER", "Summer"),
                    ("MIDSEASON", "Midseason"),
                    ("BASIC", "Basic"),
                    ("ANTIFREEZE", "Antifreeze"),
                ],
                max_length=32,
                null=True,
                verbose_name="Relay mode",
            ),
        ),
    ]
