# Generated by Django 6.0.8 on 2026-09-18 07:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("relays", "0007_relay_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="relay",
            name="state",
            field=models.CharField(
                blank=True,
                choices=[("ON", "ON"), ("OFF", "OFF"), ("IGNORED", "Ignored"), ("UNKNOWN", "Unknown")],
                max_length=32,
                null=True,
                verbose_name="Relay state",
            ),
        ),
    ]
