# Generated by Django 6.0.8 on 2026-09-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("relays", "0008_relay_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relay",
            name="state",
            field=models.CharField(
                blank=True,
                choices=[("ON", "ON"), ("OFF", "OFF"), ("UNKNOWN", "Unknown")],
                max_length=32,
                null=True,
                verbose_name="Relay state",
            ),
        ),
    ]
