# Generated by Django 6.0.8 on 2026-09-28 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("relays", "0009_alter_relay_state"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RelayLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "old_state",
                    models.CharField(
                        blank=True,
                        choices=[("ON", "ON"), ("OFF", "OFF"), ("UNKNOWN", "Unknown")],
                        max_length=32,
                        null=True,
                        verbose_name="Old state",
                    ),
                ),
                (
                    "new_state",
                    models.CharField(
                        blank=True,
                        choices=[("ON", "ON"), ("OFF", "OFF"), ("UNKNOWN", "Unknown")],
                        max_length=32,
                        null=True,
                        verbose_name="New state",
                    ),
                ),
                (
                    "old_mode",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("UNKNOWN", "Unknown"),
                            ("FALLBACK", "Fallback"),
                            ("FORCED", "Forced"),
                            ("IGNORED", "Ignored"),
                            ("SUMMER", "Summer"),
                            ("MIDSEASON", "Midseason"),
                            ("BASIC", "Basic"),
                            ("ANTIFREEZE", "Antifreeze"),
                        ],
                        max_length=32,
                        null=True,
                        verbose_name="Old mode",
                    ),
                ),
                (
                    "new_mode",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("UNKNOWN", "Unknown"),
                            ("FALLBACK", "Fallback"),
                            ("FORCED", "Forced"),
                            ("IGNORED", "Ignored"),
                            ("SUMMER", "Summer"),
                            ("MIDSEASON", "Midseason"),
                            ("BASIC", "Basic"),
                            ("ANTIFREEZE", "Antifreeze"),
                        ],
                        max_length=32,
                        null=True,
                        verbose_name="New mode",
                    ),
                ),
                (
                    "old_force_state",
                    models.CharField(
                        blank=True,
                        choices=[("ON", "ON"), ("OFF", "OFF")],
                        max_length=32,
                        null=True,
                        verbose_name="Old force state",
                    ),
                ),
                (
                    "new_force_state",
                    models.CharField(
                        blank=True,
                        choices=[("ON", "ON"), ("OFF", "OFF")],
                        max_length=32,
                        null=True,
                        verbose_name="New force state",
                    ),
                ),
                ("old_context", models.JSONField(default=dict, verbose_name="Old context")),
                ("new_context", models.JSONField(default=dict, verbose_name="New context")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                (
                    "relay",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs",
                        to="relays.relay",
                        verbose_name="Relay",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="relay_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "relay log",
                "verbose_name_plural": "relay logs",
                "ordering": ("-created_at",),
            },
        ),
    ]
