# Generated by Django 5.2.2 on 2025-07-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Music",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file", models.FileField(max_length=256, upload_to="")),
                ("meta", models.JSONField(default=dict)),
                ("album", models.CharField(blank=True, db_index=True, null=True)),
                ("artist", models.CharField(blank=True, db_index=True, null=True)),
                ("title", models.CharField(blank=True, null=True)),
                ("genre", models.CharField(blank=True, null=True)),
                ("year", models.IntegerField(blank=True, null=True)),
                ("has_cover", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "music",
                "verbose_name_plural": "music",
            },
        ),
    ]
